[[SharedMimeInfo]]
arch = "aarch64"
git-tree-sha1 = "7d1484b526ddca47334bae0e41a2f6f4a9a72bc3"
libc = "glibc"
os = "linux"

    [[SharedMimeInfo.download]]
    sha256 = "0a869bbfde73a77e9cefe2d794eabeba39d7a4619a5673a1615141a7b10876e0"
    url = "https://github.com/JuliaBinaryWrappers/SharedMimeInfo_jll.jl/releases/download/SharedMimeInfo-v1.15.0+0/SharedMimeInfo.v1.15.0.aarch64-linux-gnu.tar.gz"
[[SharedMimeInfo]]
arch = "aarch64"
git-tree-sha1 = "e9f62afffbce822cd4ca1a53d1053b5e1cc3a044"
libc = "musl"
os = "linux"

    [[SharedMimeInfo.download]]
    sha256 = "c281fb71e399e015f708d150fa3908f7fe491b7bf3b334eb2afcb28bde913fc2"
    url = "https://github.com/JuliaBinaryWrappers/SharedMimeInfo_jll.jl/releases/download/SharedMimeInfo-v1.15.0+0/SharedMimeInfo.v1.15.0.aarch64-linux-musl.tar.gz"
[[SharedMimeInfo]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c4fe600175808b63fba83cd56ce7ede8340b37af"
libc = "glibc"
os = "linux"

    [[SharedMimeInfo.download]]
    sha256 = "deed5543388daecceeac79c2ec38282cb52d50ce7bf2c1d27b309ebce13c1330"
    url = "https://github.com/JuliaBinaryWrappers/SharedMimeInfo_jll.jl/releases/download/SharedMimeInfo-v1.15.0+0/SharedMimeInfo.v1.15.0.armv7l-linux-gnueabihf.tar.gz"
[[SharedMimeInfo]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "60b41addf7028d866e7e136499778a52487518f5"
libc = "musl"
os = "linux"

    [[SharedMimeInfo.download]]
    sha256 = "aa28ad0e7762f5098921743f24f207429f847ca3b42c059daaa844dd1d10d8d5"
    url = "https://github.com/JuliaBinaryWrappers/SharedMimeInfo_jll.jl/releases/download/SharedMimeInfo-v1.15.0+0/SharedMimeInfo.v1.15.0.armv7l-linux-musleabihf.tar.gz"
[[SharedMimeInfo]]
arch = "i686"
git-tree-sha1 = "c302c35fe1727684370c81c0fbe7e6a40b0b4f53"
libc = "glibc"
os = "linux"

    [[SharedMimeInfo.download]]
    sha256 = "b9b26d7bb090ba4fc6c8eedfc5fe010a5c94a9421297dfa45649e851144e3072"
    url = "https://github.com/JuliaBinaryWrappers/SharedMimeInfo_jll.jl/releases/download/SharedMimeInfo-v1.15.0+0/SharedMimeInfo.v1.15.0.i686-linux-gnu.tar.gz"
[[SharedMimeInfo]]
arch = "i686"
git-tree-sha1 = "c5a74e1a4395eebba6b0921c0ee9bfdb23eccc99"
libc = "musl"
os = "linux"

    [[SharedMimeInfo.download]]
    sha256 = "059d19ecbbcc8817cd01cf0ec3be279b703953fe0f6130d5d4c204c22cd1dab2"
    url = "https://github.com/JuliaBinaryWrappers/SharedMimeInfo_jll.jl/releases/download/SharedMimeInfo-v1.15.0+0/SharedMimeInfo.v1.15.0.i686-linux-musl.tar.gz"
[[SharedMimeInfo]]
arch = "i686"
git-tree-sha1 = "29cc860fa61b5452207a1a939f3bb9125d89763f"
os = "windows"

    [[SharedMimeInfo.download]]
    sha256 = "43ffa5728a66329e5ec2b98f58c1b8faea93c23e2d3dec7801cda4e4b0140341"
    url = "https://github.com/JuliaBinaryWrappers/SharedMimeInfo_jll.jl/releases/download/SharedMimeInfo-v1.15.0+0/SharedMimeInfo.v1.15.0.i686-w64-mingw32.tar.gz"
[[SharedMimeInfo]]
arch = "powerpc64le"
git-tree-sha1 = "c98c78f46235e0db5b4ab81d6150e81303d0af47"
libc = "glibc"
os = "linux"

    [[SharedMimeInfo.download]]
    sha256 = "2ace9aa7e27bbf4aa374eaff9b2e7400ddb478c378d18041704613c2d0ee1f73"
    url = "https://github.com/JuliaBinaryWrappers/SharedMimeInfo_jll.jl/releases/download/SharedMimeInfo-v1.15.0+0/SharedMimeInfo.v1.15.0.powerpc64le-linux-gnu.tar.gz"
[[SharedMimeInfo]]
arch = "x86_64"
git-tree-sha1 = "2a56eaee645c681d3b1285a2144b5e9fb267741c"
os = "macos"

    [[SharedMimeInfo.download]]
    sha256 = "11f98c15196bd47f9069d0e926555e8061a7e5cf9df577695f51e48c335114fb"
    url = "https://github.com/JuliaBinaryWrappers/SharedMimeInfo_jll.jl/releases/download/SharedMimeInfo-v1.15.0+0/SharedMimeInfo.v1.15.0.x86_64-apple-darwin.tar.gz"
[[SharedMimeInfo]]
arch = "x86_64"
git-tree-sha1 = "4a7d465174d04b905265e8cfcb5bf9bc132045c3"
libc = "glibc"
os = "linux"

    [[SharedMimeInfo.download]]
    sha256 = "c9d6e3286d14c1dfb9e1596a0f45aaa52768b6fc297244ed337d02d118b9031e"
    url = "https://github.com/JuliaBinaryWrappers/SharedMimeInfo_jll.jl/releases/download/SharedMimeInfo-v1.15.0+0/SharedMimeInfo.v1.15.0.x86_64-linux-gnu.tar.gz"
[[SharedMimeInfo]]
arch = "x86_64"
git-tree-sha1 = "5356e775d3d675462aff31851483ee162d4f77e0"
libc = "musl"
os = "linux"

    [[SharedMimeInfo.download]]
    sha256 = "a78ef66005592b231aaf3c296113777630a81d2a06503448b1986ccb5361154e"
    url = "https://github.com/JuliaBinaryWrappers/SharedMimeInfo_jll.jl/releases/download/SharedMimeInfo-v1.15.0+0/SharedMimeInfo.v1.15.0.x86_64-linux-musl.tar.gz"
[[SharedMimeInfo]]
arch = "x86_64"
git-tree-sha1 = "f47327085e990ceac881c08527a140371a8bdcf7"
os = "freebsd"

    [[SharedMimeInfo.download]]
    sha256 = "84c144d9d26e7ee955258002fefbf7b0d8472f8512977e783cab3e49aefb8a94"
    url = "https://github.com/JuliaBinaryWrappers/SharedMimeInfo_jll.jl/releases/download/SharedMimeInfo-v1.15.0+0/SharedMimeInfo.v1.15.0.x86_64-unknown-freebsd.tar.gz"
[[SharedMimeInfo]]
arch = "x86_64"
git-tree-sha1 = "01ee0892a8440d23ddb781fd1de8180b0f046eb8"
os = "windows"

    [[SharedMimeInfo.download]]
    sha256 = "59188c9bd880684fb1a9fe08655eb33ecc583cd594cd03475a260ea78eaefd04"
    url = "https://github.com/JuliaBinaryWrappers/SharedMimeInfo_jll.jl/releases/download/SharedMimeInfo-v1.15.0+0/SharedMimeInfo.v1.15.0.x86_64-w64-mingw32.tar.gz"
